name: Publish Packages

on:
  release:
    types: [published]

jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: |
          pnpm --filter "@tradercore/plugin-template-types" build
          pnpm --filter "@tradercore/plugin-template-main" build

      - name: Sync version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cd packages/types && pnpm version $VERSION --no-git-tag-version
          cd ../main && pnpm version $VERSION --no-git-tag-version

      - name: Publish to NPM
        run: |
          cd packages/types && pnpm publish --no-git-checks --access public
          cd ../main && pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 